name: Build Dev APK

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build-dev:
    name: Build Dev APK
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          
      - name: Build Dev Debug APK
        run: ./gradlew assembleDevDebug --stacktrace
        
      - name: Build Dev Release APK
        run: ./gradlew assembleDevRelease --stacktrace
        
      - name: Upload Dev Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: dev-debug-apk
          path: app/build/outputs/apk/dev/debug/*.apk
          retention-days: 30
          
      - name: Upload Dev Release APK
        uses: actions/upload-artifact@v4
        with:
          name: dev-release-apk
          path: app/build/outputs/apk/dev/release/*.apk
          retention-days: 30
          
      - name: Get APK Info
        run: |
          echo "### Dev Build Information" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Build Type:** Dev" >> $GITHUB_STEP_SUMMARY
          echo "**Branch:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "**Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ -f app/build/outputs/apk/dev/debug/*.apk ]; then
            DEBUG_SIZE=$(du -h app/build/outputs/apk/dev/debug/*.apk | cut -f1)
            echo "**Debug APK Size:** $DEBUG_SIZE" >> $GITHUB_STEP_SUMMARY
          fi
          
          if [ -f app/build/outputs/apk/dev/release/*.apk ]; then
            RELEASE_SIZE=$(du -h app/build/outputs/apk/dev/release/*.apk | cut -f1)
            echo "**Release APK Size:** $RELEASE_SIZE" >> $GITHUB_STEP_SUMMARY
          fi
