name: Build All Flavors

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-all:
    name: Build All Flavors
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        flavor: [dev, qa, prod]
        buildType: [debug, release]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_HOME" > local.properties
          
      - name: Build ${{ matrix.flavor }} ${{ matrix.buildType }} APK
        run: |
          FLAVOR_CAP=$(echo ${{ matrix.flavor }} | sed 's/./\U&/')
          BUILD_TYPE_CAP=$(echo ${{ matrix.buildType }} | sed 's/./\U&/')
          ./gradlew assemble${FLAVOR_CAP}${BUILD_TYPE_CAP} --stacktrace
          
      - name: Upload ${{ matrix.flavor }} ${{ matrix.buildType }} APK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.flavor }}-${{ matrix.buildType }}-apk
          path: app/build/outputs/apk/${{ matrix.flavor }}/${{ matrix.buildType }}/*.apk
          retention-days: 30
          
  summary:
    name: Build Summary
    runs-on: ubuntu-latest
    needs: build-all
    if: always()
    
    steps:
      - name: Create Summary
        run: |
          echo "### Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Branch:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "**Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "**Triggered by:** ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "All flavor builds completed!" >> $GITHUB_STEP_SUMMARY
